### ISSUE TITLE
Issue with throttle devices which  have multiple device instances, aka. 'InstanceGuid' (here Saitek X55 Rhino)

### ISSUE THREAD

**Issue by Althar93** [mrkline/bms-burner#7]
It would appear that the logic for getting hold of the joystick is to just use the ProductGuid ; this works in most cases, except when the device in question has **multiple instances** & choosing the first one might not be correct.

In my case, I have a Saitek X55 Rhino, which has two device entries (when querying 'GetDevices' from the DirectInput). The first entry is not of the correct one (wrong subtype and reports 0 axes in the Capabilities) & this results in an invalid device being used for the rest of the program & the throttle state subsequently always being 100%.

I spent 30 minutes investigating & made some minor changes locally to bms-burner to look for the first device of the ProductGuid family which has at least one axis which fixes the issue in my case : 

```
// Look for all throttle devices matching the product Guid
var allDevices      = input.GetDevices();
var throttleDevices = allDevices.Where(Device => Device.ProductGuid == bmsConfig.ThrottleDeviceGUID);

// Iterate through all instances
foreach (var throttleDevice in throttleDevices)
{
    throttle?.Dispose();
    throttle = new Joystick(input, throttleDevice.InstanceGuid);
    throttle.Properties.BufferSize = 128;
    throttle.Acquire();

    // Make sure we have at least one axis
    if (throttle.Capabilities.AxeCount > 0 )
    {
        break;
    }
}
```
I am not saying the above is the correct fix but might be worth looking into further to establish what the correct behaviour / flow should be with respect to multiple devices sharing the same product Guid.

**Comment by mrkline** [comment]
Sorry for the very long delay - meatspace has been hectic. That code (or something very close to it) seems to work well! One dumb question: What's the purpose of setting the throttle's `BufferSize` before acquiring it?

**Comment by Althar93** [comment]
The 'BufferSize' is used to enable input buffering according to the documentation. I don't think it is strictly required here, it was more a remnance of me trying different things & thinking at the time my issue might be related & then I forgot to remove it (not that it should cause any harm.
